-- ============================================================
-- DistrictPilot AI: Feature Mart v4 (확인된 실제 값 기반)
-- SGG='서초구' | REGION_LEVEL='sgg' | MOVEMENT_TYPE='전입'/'전출'
-- ============================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DISTRICTPILOT_AI;
USE SCHEMA ANALYTICS;

-- ============================================================
-- 1. SPH 유동인구 (구별 월별)
-- ============================================================
CREATE OR REPLACE TABLE STG_POP AS
SELECT
    FP.STANDARD_YEAR_MONTH AS YM,
    SM.CITY_KOR_NAME AS DISTRICT,
    SUM(FP.RESIDENTIAL_POPULATION) AS RES_POP,
    SUM(FP.WORKING_POPULATION) AS WORK_POP,
    SUM(FP.VISITING_POPULATION) AS VISIT_POP,
    SUM(FP.RESIDENTIAL_POPULATION + FP.WORKING_POPULATION + FP.VISITING_POPULATION) AS TOTAL_POP
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.FLOATING_POPULATION_INFO FP
JOIN SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST SM
    ON FP.DISTRICT_CODE = SM.DISTRICT_CODE
WHERE SM.CITY_KOR_NAME IN ('서초구','영등포구','중구')
GROUP BY FP.STANDARD_YEAR_MONTH, SM.CITY_KOR_NAME;

-- ============================================================
-- 2. SPH 카드소비 (구별 월별)
-- ============================================================
CREATE OR REPLACE TABLE STG_CARD AS
SELECT
    CS.STANDARD_YEAR_MONTH AS YM,
    SM.CITY_KOR_NAME AS DISTRICT,
    SUM(CS.TOTAL_SALES) AS TOTAL_SALES,
    SUM(CS.FOOD_SALES) AS FOOD,
    SUM(CS.COFFEE_SALES) AS COFFEE,
    SUM(CS.ENTERTAINMENT_SALES) AS ENTERTAIN,
    SUM(CS.CLOTHING_ACCESSORIES_SALES) AS CLOTHING,
    SUM(CS.SPORTS_CULTURE_LEISURE_SALES) AS CULTURE,
    SUM(CS.ACCOMMODATION_SALES) AS ACCOMMODATION,
    SUM(CS.BEAUTY_SALES) AS BEAUTY,
    SUM(CS.MEDICAL_SALES) AS MEDICAL,
    SUM(CS.EDUCATION_ACADEMY_SALES) AS EDUCATION,
    SUM(CS.TOTAL_COUNT) AS TOTAL_TX_COUNT
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CARD_SALES_INFO CS
JOIN SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST SM
    ON CS.DISTRICT_CODE = SM.DISTRICT_CODE
WHERE SM.CITY_KOR_NAME IN ('서초구','영등포구','중구')
GROUP BY CS.STANDARD_YEAR_MONTH, SM.CITY_KOR_NAME;

-- ============================================================
-- 3. SPH 자산소득 (구별 월별)
-- ============================================================
CREATE OR REPLACE TABLE STG_ASSET AS
SELECT
    AI.STANDARD_YEAR_MONTH AS YM,
    SM.CITY_KOR_NAME AS DISTRICT,
    SUM(AI.CUSTOMER_COUNT) AS CUSTOMERS,
    AVG(AI.AVERAGE_INCOME) AS AVG_INCOME,
    AVG(AI.AVERAGE_ASSET_AMOUNT) AS AVG_ASSET,
    AVG(AI.AVERAGE_SCORE) AS AVG_CREDIT_SCORE,
    AVG(AI.AVERAGE_HOUSEHOLD_INCOME) AS AVG_HH_INCOME
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.ASSET_INCOME_INFO AI
JOIN SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST SM
    ON AI.DISTRICT_CODE = SM.DISTRICT_CODE
WHERE SM.CITY_KOR_NAME IN ('서초구','영등포구','중구')
GROUP BY AI.STANDARD_YEAR_MONTH, SM.CITY_KOR_NAME;

-- ============================================================
-- 4. Richgo 시세 (구별 월별) — REGION_LEVEL='sgg' (소문자!)
-- ============================================================
CREATE OR REPLACE TABLE STG_PRICE AS
SELECT
    TO_CHAR(YYYYMMDD, 'YYYYMM') AS YM,
    SGG AS DISTRICT,
    AVG(MEME_PRICE_PER_SUPPLY_PYEONG) AS AVG_MEME_PRICE,
    AVG(JEONSE_PRICE_PER_SUPPLY_PYEONG) AS AVG_JEONSE_PRICE,
    AVG(MEME_PRICE_PER_SUPPLY_PYEONG) AS AVG_PRICE_PER_PYEONG,
    SUM(TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA.HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H
WHERE SGG IN ('서초구','영등포구','중구')
GROUP BY TO_CHAR(YYYYMMDD, 'YYYYMM'), SGG;

-- ============================================================
-- 5. 인구이동 (합성 — Marketplace 리스팅에 REGION_POPULATION_MOVEMENT 미포함)
-- 서울시 인구이동 통계(KOSIS) 기반 현실적인 전입/전출 패턴 재현
-- Production에서는 행정안전부 전입신고 API로 교체
-- ============================================================
CREATE OR REPLACE TABLE STG_MOVE AS
WITH months AS (
    SELECT DISTINCT YM FROM STG_POP
),
districts AS (
    SELECT '서초구' AS DISTRICT, 4200 AS BASE_IN, 3900 AS BASE_OUT UNION ALL
    SELECT '영등포구',           3800,             3600            UNION ALL
    SELECT '중구',              1200,             1350
),
base AS (
    SELECT m.YM, d.DISTRICT, d.BASE_IN, d.BASE_OUT,
        CAST(SUBSTRING(m.YM, 5, 2) AS INT) AS MM,
        CASE CAST(SUBSTRING(m.YM, 5, 2) AS INT)
            WHEN 1 THEN 0.85 WHEN 2 THEN 0.95 WHEN 3 THEN 1.25
            WHEN 4 THEN 1.10 WHEN 5 THEN 1.05 WHEN 6 THEN 0.95
            WHEN 7 THEN 0.90 WHEN 8 THEN 0.85 WHEN 9 THEN 1.20
            WHEN 10 THEN 1.10 WHEN 11 THEN 1.00 WHEN 12 THEN 0.90
        END AS SEASON,
        1 + (CAST(SUBSTRING(m.YM, 1, 4) AS INT) - 2020) * 0.02 AS TREND
    FROM months m CROSS JOIN districts d
)
SELECT YM, DISTRICT,
    ROUND(BASE_IN * SEASON * TREND)  AS MOVE_IN,
    ROUND(BASE_OUT * SEASON * TREND) AS MOVE_OUT,
    ROUND(BASE_IN * SEASON * TREND) - ROUND(BASE_OUT * SEASON * TREND) AS NET_MOVE
FROM base
ORDER BY YM, DISTRICT;

-- ============================================================
-- 6. 통합 Feature Mart
-- ============================================================
CREATE OR REPLACE TABLE FEATURE_MART_FINAL AS
SELECT
    p.YM,
    p.DISTRICT,
    -- 유동인구
    p.TOTAL_POP, p.RES_POP, p.WORK_POP, p.VISIT_POP,
    -- 카드소비
    c.TOTAL_SALES, c.FOOD, c.COFFEE, c.ENTERTAIN, c.CLOTHING, c.CULTURE,
    c.ACCOMMODATION, c.BEAUTY, c.MEDICAL, c.EDUCATION, c.TOTAL_TX_COUNT,
    -- 자산소득
    a.CUSTOMERS, a.AVG_INCOME, a.AVG_ASSET, a.AVG_CREDIT_SCORE, a.AVG_HH_INCOME,
    -- 부동산
    r.AVG_MEME_PRICE, r.AVG_JEONSE_PRICE, r.AVG_PRICE_PER_PYEONG, r.TOTAL_HOUSEHOLDS,
    -- 인구이동
    m.MOVE_IN, m.MOVE_OUT, m.NET_MOVE,
    -- 파생 피처
    CASE WHEN p.TOTAL_POP > 0 THEN c.TOTAL_SALES / p.TOTAL_POP ELSE 0 END AS SALES_PER_POP,
    CASE WHEN a.AVG_ASSET > 0 THEN r.AVG_MEME_PRICE / a.AVG_ASSET ELSE NULL END AS PRICE_TO_ASSET_RATIO,
    LAG(c.TOTAL_SALES) OVER (PARTITION BY p.DISTRICT ORDER BY p.YM) AS PREV_SALES,
    LAG(p.TOTAL_POP) OVER (PARTITION BY p.DISTRICT ORDER BY p.YM) AS PREV_POP,
    CASE WHEN LAG(c.TOTAL_SALES) OVER (PARTITION BY p.DISTRICT ORDER BY p.YM) > 0
         THEN (c.TOTAL_SALES - LAG(c.TOTAL_SALES) OVER (PARTITION BY p.DISTRICT ORDER BY p.YM))
              / LAG(c.TOTAL_SALES) OVER (PARTITION BY p.DISTRICT ORDER BY p.YM) * 100
         ELSE 0 END AS SALES_CHG_PCT,
    CASE WHEN LAG(p.TOTAL_POP) OVER (PARTITION BY p.DISTRICT ORDER BY p.YM) > 0
         THEN (p.TOTAL_POP - LAG(p.TOTAL_POP) OVER (PARTITION BY p.DISTRICT ORDER BY p.YM))
              / LAG(p.TOTAL_POP) OVER (PARTITION BY p.DISTRICT ORDER BY p.YM) * 100
         ELSE 0 END AS POP_CHG_PCT,
    CASE WHEN LAG(r.AVG_MEME_PRICE) OVER (PARTITION BY p.DISTRICT ORDER BY p.YM) > 0
         THEN (r.AVG_MEME_PRICE - LAG(r.AVG_MEME_PRICE) OVER (PARTITION BY p.DISTRICT ORDER BY p.YM))
              / LAG(r.AVG_MEME_PRICE) OVER (PARTITION BY p.DISTRICT ORDER BY p.YM) * 100
         ELSE 0 END AS PRICE_CHG_PCT
FROM STG_POP p
LEFT JOIN STG_CARD c ON p.YM = c.YM AND p.DISTRICT = c.DISTRICT
LEFT JOIN STG_ASSET a ON p.YM = a.YM AND p.DISTRICT = a.DISTRICT
LEFT JOIN STG_PRICE r ON p.YM = r.YM AND p.DISTRICT = r.DISTRICT
LEFT JOIN STG_MOVE m ON p.YM = m.YM AND p.DISTRICT = m.DISTRICT
ORDER BY p.YM, p.DISTRICT;

-- ============================================================
-- 확인
-- ============================================================
SELECT * FROM FEATURE_MART_FINAL ORDER BY YM DESC, DISTRICT LIMIT 15;
SELECT DISTRICT, MIN(YM) AS START_YM, MAX(YM) AS END_YM, COUNT(*) AS MONTHS FROM FEATURE_MART_FINAL GROUP BY DISTRICT;
