USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DISTRICTPILOT_AI;
USE SCHEMA ANALYTICS;

SELECT CURRENT_ACCOUNT() AS ACCOUNT_NAME,
       CURRENT_REGION() AS REGION_NAME,
       CURRENT_ROLE() AS ROLE_NAME,
       CURRENT_WAREHOUSE() AS WAREHOUSE_NAME,
       CURRENT_DATABASE() AS DATABASE_NAME,
       CURRENT_SCHEMA() AS SCHEMA_NAME;

SHOW DATABASES LIKE 'DISTRICTPILOT_AI';
SHOW MODELS LIKE 'DISTRICTPILOT_FORECAST%';
SHOW SEMANTIC VIEWS LIKE 'DISTRICTPILOT_SV';
SHOW CORTEX SEARCH SERVICES LIKE 'DISTRICTPILOT_SEARCH_SVC';
SHOW STREAMLITS LIKE 'DISTRICTPILOT_APP';
SHOW STREAMLITS;

SELECT COUNT(*) AS FEATURE_MART_V3_ROWS FROM FEATURE_MART_V3;
SELECT COUNT(*) AS FEATURE_MART_V2_ROWS FROM FEATURE_MART_V2;
SELECT COUNT(*) AS STG_TELECOM_ROWS FROM STG_TELECOM;
SELECT COUNT(*) AS FORECAST_RESULTS_ROWS FROM FORECAST_RESULTS;
SELECT COUNT(*) AS ACTUAL_VS_FORECAST_ROWS FROM ACTUAL_VS_FORECAST;
SELECT COUNT(*) AS FEATURE_IMPORTANCE_ROWS FROM FEATURE_IMPORTANCE;
SELECT COUNT(*) AS ABLATION_RESULTS_ROWS FROM ABLATION_RESULTS;

DESCRIBE TABLE ABLATION_RESULTS;
SELECT * FROM ABLATION_RESULTS LIMIT 10;
SELECT * FROM FEATURE_IMPORTANCE LIMIT 10;
SELECT * FROM V_APP_HEALTH;

SHOW VIEWS LIKE 'DISTRICTPILOT_SV' IN SCHEMA DISTRICTPILOT_AI.ANALYTICS; -- Semantic View 존재 확인

SELECT NAME, STATE, COMPLETED_TIME
FROM TABLE(
  INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('day', -7, CURRENT_TIMESTAMP())
  )
)
WHERE DATABASE_NAME = 'DISTRICTPILOT_AI'
  AND SCHEMA_NAME = 'ANALYTICS'
ORDER BY COMPLETED_TIME DESC
LIMIT 10;
