USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DISTRICTPILOT_AI;
USE SCHEMA ANALYTICS;

-- 1. Live stack identity
SELECT CURRENT_ACCOUNT() AS ACCOUNT_NAME,
       CURRENT_REGION() AS REGION_NAME,
       CURRENT_ROLE() AS ROLE_NAME,
       CURRENT_WAREHOUSE() AS WAREHOUSE_NAME,
       CURRENT_DATABASE() AS DATABASE_NAME,
       CURRENT_SCHEMA() AS SCHEMA_NAME,
       CURRENT_TIMESTAMP() AS CHECKED_AT;

SHOW DATABASES LIKE 'DISTRICTPILOT_AI';
SHOW MODELS LIKE 'DISTRICTPILOT_FORECAST%' IN SCHEMA DISTRICTPILOT_AI.ANALYTICS;
SHOW SEMANTIC VIEWS LIKE 'DISTRICTPILOT_SV';
SHOW CORTEX SEARCH SERVICES LIKE 'DISTRICTPILOT_SEARCH_SVC';
SHOW STREAMLITS LIKE 'DISTRICTPILOT_APP';
SHOW STREAMLITS;

-- 2. Evidence chain row counts
SELECT 'FEATURE_MART_V3' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM FEATURE_MART_V3
UNION ALL
SELECT 'FEATURE_MART_V2' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM FEATURE_MART_V2
UNION ALL
SELECT 'STG_TELECOM' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM STG_TELECOM
UNION ALL
SELECT 'FORECAST_RESULTS' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM FORECAST_RESULTS
UNION ALL
SELECT 'ACTUAL_VS_FORECAST' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM ACTUAL_VS_FORECAST
UNION ALL
SELECT 'FEATURE_IMPORTANCE' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM FEATURE_IMPORTANCE
UNION ALL
SELECT 'ABLATION_RESULTS' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM ABLATION_RESULTS
ORDER BY OBJECT_NAME;

-- 2b. AJD rental signal verification
SELECT DISTRICT,
       ROUND(AVG(RENTAL_COUNT)) AS AVG_RENTAL,
       ROUND(AVG(RENTAL_CONVERSION_RATE), 4) AS AVG_CONV_RATE,
       ROUND(AVG(RENTAL_SIGNAL), 2) AS AVG_SIGNAL
FROM FEATURE_MART_V3
WHERE YM >= '202401'
GROUP BY DISTRICT
ORDER BY AVG_SIGNAL DESC;

-- 3. Forecast rigor
SELECT * FROM ABLATION_RESULTS LIMIT 15;
SELECT * FROM FEATURE_IMPORTANCE LIMIT 10;

-- 4. AI / semantic / ops trust
SHOW VIEWS LIKE 'DISTRICTPILOT_SV' IN SCHEMA DISTRICTPILOT_AI.ANALYTICS; -- Semantic View 존재 확인
SELECT * FROM V_APP_HEALTH;
