USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DISTRICTPILOT_AI;
USE SCHEMA ANALYTICS;

-- 1. Live stack identity
SELECT CURRENT_ACCOUNT() AS ACCOUNT_NAME,
       CURRENT_REGION() AS REGION_NAME,
       CURRENT_ROLE() AS ROLE_NAME,
       CURRENT_WAREHOUSE() AS WAREHOUSE_NAME,
       CURRENT_DATABASE() AS DATABASE_NAME,
       CURRENT_SCHEMA() AS SCHEMA_NAME,
       CURRENT_TIMESTAMP() AS CHECKED_AT;

SHOW MODELS LIKE 'DISTRICTPILOT_FORECAST%' IN SCHEMA DISTRICTPILOT_AI.ANALYTICS;
SHOW SEMANTIC VIEWS LIKE 'DISTRICTPILOT_SV';
SHOW CORTEX SEARCH SERVICES LIKE 'DISTRICTPILOT_SEARCH_SVC';
SHOW STREAMLITS;

-- 2. Evidence chain row counts
SELECT 'FEATURE_MART_V2' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM FEATURE_MART_V2
UNION ALL
SELECT 'FORECAST_RESULTS' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM FORECAST_RESULTS
UNION ALL
SELECT 'ACTUAL_VS_FORECAST' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM ACTUAL_VS_FORECAST
UNION ALL
SELECT 'FEATURE_IMPORTANCE' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM FEATURE_IMPORTANCE
UNION ALL
SELECT 'ABLATION_RESULTS' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM ABLATION_RESULTS
ORDER BY OBJECT_NAME;

-- 3. Forecast rigor
SELECT * FROM ABLATION_RESULTS LIMIT 15;
SELECT * FROM FEATURE_IMPORTANCE LIMIT 10;

-- 4. AI / semantic / ops trust
SELECT SYSTEM$VALIDATE_SEMANTIC_VIEW('DISTRICTPILOT_AI.ANALYTICS.DISTRICTPILOT_SV') AS SEMANTIC_VALIDATION;
SELECT * FROM V_APP_HEALTH;
